# Generated by Django 4.2 on 2023-04-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="car_images")),
                ("description", models.TextField()),
                ("daily_rent", models.IntegerField()),
                ("is_available", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("booking_start_date", models.DateField()),
                ("booking_end_date", models.DateField()),
                ("is_approved", models.BooleanField(default=False)),
                ("car", models.ManyToManyField(to="rental.car")),
            ],
        ),
    ]
