# Generated by Django 4.2 on 2023-04-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("booking_start_date", models.DateField()),
                ("booking_end_date", models.DateField()),
                ("is_approved", models.BooleanField(default=False)),
                ("car", models.ManyToManyField(to="rental.car")),
            ],
        ),
    ]
